on: push

jobs:
  format-pr-comment:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - run: mkdir repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: repo
          ref: master

      - run: mkdir dev_scripts
      # - run: npm --prefix repo install

      - name: Check out dev scripts
        uses: actions/checkout@v2
        with:
          repository: SynapseUI/dev_scripts
          token: "${{ secrets.TEST_PAT }}"
          path: 'dev_scripts'

      # - run: cd repo
      - run: ls -la repo
      - run: ls -la dev_scripts
      - run: git -C repo branch
      # - run: git -C repo diff --name-only master..test-branch

