on: 
  pull_request:
    types: [opened]

jobs:
  format-pr-description:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - run: mkdir repo
      - name: Checkout code into repo dir
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: repo

      - run: mkdir dev_scripts

      - name: Check out dev_scripts
        uses: actions/checkout@v2
        with:
          repository: SynapseUI/dev_scripts
          token: "${{ secrets.GH_PAT_PRMD }}"
          path: 'dev_scripts'

      - name: Run devscripts
        run: |
          node \
          dev_scripts/makePrDesc/ \
          --repo-dir=repo \
          --file-name=pr_desc \
          ${{ github.head_ref }} ${{ github.base_ref }}

      - id: get-comment-body
        run: |
          body="$(cat .prMarkdown/pr_desc.md)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: pr update
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GH_PAT_PRMD }}"
          base-branch-regex: '.*'
          body-template: ${{ steps.get-comment-body.outputs.body }}
          body-update-action: 'replace'
          body-uppercase-base-match: false
