on: push

jobs:
  format-pr-comment:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - run: mkdir repo
      - name: Checkout code into repo dir
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: repo

      - run: npm --prefix repo install
      - run: mkdir dev_scripts



      - name: Check out dev_scripts
        uses: actions/checkout@v2
        with:
          repository: SynapseUI/dev_scripts
          token: "${{ secrets.TEST_PAT }}"
          path: 'dev_scripts'

      - name: Run devscripts
      - run: |
          node \
          dev_scripts/scripts/makePrMarkdown.js \
          --print-only \
          --repo-dir=repo \
          test-branch master
      # - run: git -C repo diff --name-only origin/master..
      # - run: git --git-dir=repo --work-tree=diff_dir diff --name-only --no-index
      # - run: git -C repo diff --name-only master..test-branch

