on: push

jobs:
  format-pr-comment:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - run: mkdir repo
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: repo
      - run: mkdir dev_scripts
      - run: npm --prefix repo install

      - name: Check out dev scripts
        uses: actions/checkout@v2
        with:
          repository: SynapseUI/dev_scripts
          token: "${{ secrets.TEST_PAT }}"
          path: 'dev_scripts'

      - run: cd repo
      - run: ls -la
      - name: testing git diff action
        uses: technote-space/get-diff-action@v4

