# on: push
on: pull_request

jobs:
  format-pr-comment:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - run: mkdir repo
      - name: Checkout code into repo dir
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: repo

      - run: mkdir dev_scripts

      - name: Check out dev_scripts
        uses: actions/checkout@v2
        with:
          repository: SynapseUI/dev_scripts
          token: "${{ secrets.TEST_PAT }}"
          path: 'dev_scripts'

      - name: Run devscripts
        run: |
          node \
          dev_scripts/scripts/makePrMarkdown.js \
          --repo-dir=repo \
          --file-name=comment_body \
          ${{ github.head_ref }} ${{ github.base_ref }}

      - name: show new file
        run: cat .prMarkdown/comment_body.md

      - id: get-comment-body
        run: |
          body="$(cat .prMarkdown/comment_body.md)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: ${{ github.event.pull_request.user.login }}
          token: "${{ secrets.TEST_PAT }}"

      - run: echo '${{ steps.fc.outputs.comment-id }}'
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.get-comment-body.outputs.body }}
          token: "${{ secrets.TEST_PAT }}"
